
  CREATE TABLE "A337PATE"."FINANCE_RECORD" 
   (	"HEALTH_CARD_NUMBER" NUMBER(*,0) NOT NULL ENABLE, 
	"PAYMENT_PROGRAM" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRIVATE_INSURANCE" CHAR(100 BYTE), 
	"ADMISSION_DATE" DATE NOT NULL ENABLE, 
	"DISCHARGE_DATE" DATE NOT NULL ENABLE, 
	"STATUS_CHARGE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ACCESSED_AMOUNT" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"BILLING_ADDRESS" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "FINANCE_RECORD_PK" PRIMARY KEY ("HEALTH_CARD_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;

