
  CREATE TABLE "A337PATE"."MEDICINE_RECORD" 
   (	"HEALTH_CARD_NUMBER" NUMBER(*,0) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"DOSAGE" NUMBER(3,1) NOT NULL ENABLE, 
	"MEDICINE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"SIDE_EFFECTS_NOTES" VARCHAR2(200 BYTE), 
	 FOREIGN KEY ("HEALTH_CARD_NUMBER")
	  REFERENCES "A337PATE"."MEDICAL_RECORD" ("HEALTH_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;

