//DOCTOR

  CREATE TABLE "A337PATE"."DOCTOR" 
   (	"DOC_ID" NUMBER NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "DOCTOR_ID" FOREIGN KEY ("DOC_ID")
	  REFERENCES "A337PATE"."STAFF_PROFILE" ("STAFF_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;




//FINANCE_RECORD

  CREATE TABLE "A337PATE"."FINANCE_RECORD" 
   (	"HEALTH_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PAYMENT_PROGRAM" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRIVATE_INSURANCE" CHAR(100 BYTE) NOT NULL ENABLE, 
	"ADMISSION_DATE" DATE NOT NULL ENABLE, 
	"DISCHARGE_DATE" DATE NOT NULL ENABLE, 
	"STATUS_CHARGE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ACCESSED_AMOUNT" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"BILLING_ADDRESS" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "FINANCE_RECORD_PK" PRIMARY KEY ("HEALTH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DBCOURSE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;




//GENERAL_INFO_RECORD

  CREATE TABLE "A337PATE"."GENERAL_INFO_RECORD" 
   (	"HEALTH_ID" NUMBER NOT NULL ENABLE, 
	"BLOOD_TYPE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"WEIGHT" NUMBER(3,1) NOT NULL ENABLE, 
	"BLOOD_PRESSURE" NUMBER(3,0) NOT NULL ENABLE, 
	"TEMPERATURE" NUMBER(3,1) NOT NULL ENABLE, 
	"HEIGHT" NUMBER(3,0) NOT NULL ENABLE, 
	"ALLERGY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ALLERGY_REACTION" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	 FOREIGN KEY ("HEALTH_ID")
	  REFERENCES "A337PATE"."MEDICAL_RECORD" ("HEALTH_CARD_NUMBER") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;




//LABORATORY_RECORD

  CREATE TABLE "A337PATE"."LABORATORY_RECORD" 
   (	"HEALTH_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LAB_RESULT" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ORDERING_DOCTOR" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MLT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MEDICAL_SCANS" VARCHAR2(200 BYTE), 
	"LAB_TEST" VARCHAR2(100 BYTE), 
	 FOREIGN KEY ("HEALTH_ID")
	  REFERENCES "A337PATE"."MEDICAL_RECORD" ("HEALTH_CARD_NUMBER") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;



//MLT

  CREATE TABLE "A337PATE"."MLT" 
   (	"MLT_ID" NUMBER NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "MEDICAL_LABORATORY_TECHNI_FK1" FOREIGN KEY ("MLT_ID")
	  REFERENCES "A337PATE"."STAFF_PROFILE" ("STAFF_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;




//MEDICAL_RECORD

  CREATE TABLE "A337PATE"."MEDICAL_RECORD" 
   (	"HEALTH_CARD_NUMBER" NUMBER(10,0), 
	 PRIMARY KEY ("HEALTH_CARD_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DBCOURSE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;




//MEDICINE_RECORD

  CREATE TABLE "A337PATE"."MEDICINE_RECORD" 
   (	"HEALTH_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"DOSAGE" NUMBER(3,1) NOT NULL ENABLE, 
	"MEDICINE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"SIDE_EFFECTS_NOTES" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	 FOREIGN KEY ("HEALTH_ID")
	  REFERENCES "A337PATE"."MEDICAL_RECORD" ("HEALTH_CARD_NUMBER") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;





//NURSE

  CREATE TABLE "A337PATE"."NURSE" 
   (	"NURSE_ID" NUMBER NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "NURSE_FK1" FOREIGN KEY ("NURSE_ID")
	  REFERENCES "A337PATE"."STAFF_PROFILE" ("STAFF_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;




//PATIENT_PROFILE

  CREATE TABLE "A337PATE"."PATIENT_PROFILE" 
   (	"HEALTH_CARD_NUMBER" NUMBER(10,0) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PATIENT_PROFILE_PK" PRIMARY KEY ("HEALTH_CARD_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DBCOURSE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;





//PERSONAL_RECORD

  CREATE TABLE "A337PATE"."PERSONAL_RECORD" 
   (	"FIRST_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PATIENT_ADDRESS" VARCHAR2(400 BYTE) NOT NULL ENABLE, 
	"HEALTH_CARD_NUMBER" NUMBER NOT NULL ENABLE, 
	"PHONE_NUMBER" NUMBER NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"AGE" NUMBER NOT NULL ENABLE, 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;





//RECEPTIONIST

  CREATE TABLE "A337PATE"."RECEPTIONIST" 
   (	"RECEPTIONIST_ID" NUMBER NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "RECEPTIONIST_ID" FOREIGN KEY ("RECEPTIONIST_ID")
	  REFERENCES "A337PATE"."STAFF_PROFILE" ("STAFF_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;





//STAFF_PROFILE

  CREATE TABLE "A337PATE"."STAFF_PROFILE" 
   (	"STAFF_ID" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DBCOURSE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;




//SURGERY_RECORD

  CREATE TABLE "A337PATE"."SURGERY_RECORD" 
   (	"HEALTH_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SURGERY" VARCHAR2(500 BYTE), 
	"SURGEON_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 FOREIGN KEY ("HEALTH_ID")
	  REFERENCES "A337PATE"."MEDICAL_RECORD" ("HEALTH_CARD_NUMBER") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;



