
  CREATE TABLE "A337PATE"."STAFF_PROFILE" 
   (	"STAFF_ID"  NUMBER(*,0), 
	   "PASSWORD"   VARCHAR2(20 BYTE), 
	   PRIMARY KEY ("STAFF_ID")
     
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DBCOURSE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;

