
  CREATE TABLE "A337PATE"."SURGERY_RECORD" 
   (	"HEALTH_CARD_NUMBER" NUMBER(*,0) NOT NULL ENABLE, 
	"SURGERY" VARCHAR2(500 BYTE), 
	"DOCTOR_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"DATE_OF_SURGERY" DATE NOT NULL ENABLE, 
	"PRESCRIBED_MED" CHAR(1 BYTE), 
	 FOREIGN KEY ("HEALTH_CARD_NUMBER")
	  REFERENCES "A337PATE"."MEDICAL_RECORD" ("HEALTH_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;

